# -*- coding: utf-8 -*-
"""NlpProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCCpHWeosXNxko79VXemLcYJbFueSmRw

# SET UP LIBRARIES + CONSTANT
"""

!pip install --upgrade pip
!pip install transformers datasets accelerate evaluate seqeval
!pip install peft bitsandbytes
!pip install git+https://github.com/unslothai/unsloth.git
!pip install --upgrade transformers
!pip install evaluate

import torch
print(torch.cuda.is_available())

MODEL_NAME = "microsoft/codebert-base"

"""# LOAD DATASET + PREPROCESSING"""

# load dataset
from datasets import load_dataset
ds = load_dataset("DaniilOr/SemEval-2026-Task13", 'A')
for split in ds:
    print(split, len(ds[split]))

import os
import shutil
import zipfile
from datasets import load_from_disk
from transformers import AutoTokenizer

zip_path = "/content/tokenized_dataset.zip"
temp_dir = "/content/temp_tokenized_data"

if os.path.exists(zip_path):
    print(f"Found existing {zip_path}")

    if os.path.exists(temp_dir):
      shutil.rmtree(temp_dir)
    os.makedirs(temp_dir)

    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(temp_dir)

    print(f"Loading dataset from {temp_dir}...")
    tokenized = load_from_disk(temp_dir)
    shutil.rmtree(temp_dir)
else:

    print(f"{zip_path} not found. Starting new tokenization process...")

    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

    def tokenize_batch(ex):
        return tokenizer(ex["code"], truncation=True, padding="max_length", max_length=512)

    tokenized = ds.map(tokenize_batch, batched=True, remove_columns=["code", "generator", "language"])
    tokenized = tokenized.rename_column("label", "labels")
    tokenized.set_format("torch")


    tokenized.save_to_disk(temp_dir)

    shutil.make_archive(base_name=zip_path.replace(".zip", ""), format='zip', root_dir=temp_dir, base_dir=".")
    shutil.rmtree(temp_dir)

print("Tokenization done!")

from transformers import AutoModelForSequenceClassification, AutoTokenizer
from peft import LoraConfig, get_peft_model, TaskType

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    target_modules=["query", "value"],
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.SEQ_CLS
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

"""# MODEL TRAINING

"""

# training
from transformers import TrainingArguments, Trainer
import evaluate

metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = logits.argmax(-1)
    return metric.compute(predictions=preds, references=labels)

training_args = TrainingArguments(
    output_dir="/content/sem_eval_task13_lora",
    per_device_train_batch_size=128,
    per_device_eval_batch_size=128,
    num_train_epochs=1,
    fp16=True,
    eval_strategy="steps",
    save_strategy="steps",
    eval_steps=500,
    save_steps=500,
    learning_rate=1e-4,
    weight_decay=0.05,
    logging_steps=10000,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    logging_dir="/content/sem_eval_task13_logs",
    dataloader_num_workers=8,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized["train"],
    eval_dataset=tokenized["validation"],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

trainer.train()
trainer.evaluate()

model.save_pretrained("/content/sem_eval_task13_lora_adapter")

"""# TEST DATA AND METRICS"""

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

predictions_output = trainer.predict(tokenized["test"])

print("--- Metrics from compute_metrics ---")
print(predictions_output.metrics)
print("\n")

y_pred = np.argmax(predictions_output.predictions, axis=1)
y_true = predictions_output.label_ids

print("--- Classification Report (with Macro F1) ---")
print(classification_report(y_true, y_pred, digits=4))
print("\n")

print("--- Confusion Matrix ---")
print(confusion_matrix(y_true, y_pred))